ojo-network/price-feeder

cmd/price-feeder.go, go.mod, go.sum, price-feeder.example.toml
* Updates to the latest version of the Ojo binary 
* Sets the bech32 prefix appropriately
* Updates the config to use the default "alice" validator & chain-id generated by `ignite chain serve --reset-once`
---
I have...
I have...
=> chore(deps): update ojo version & default config

oracle/provider/binance.go, oracle/provider/bitget.go, oracle/provider/coinbase.go, oracle/provider/gate.go, oracle/provider/mexc.go, oracle/provider/okx.go, oracle/provider/osmosisv2.go
closes: #9 
---
I have...
I have...
=> chore: Check websocket message type in all providers

.goreleaser.yml, LICENSE
closes: #XXXX
---
I have...
I have...
=> ci: fix goreleaser

go.mod, go.sum, price-feeder.example.toml
Update ojo version
---
I have...
I have...
=> chore(deps): update ojo

.goreleaser.yml
Fix goreleaser
---
I have...
I have...
=> ci: fix goreleaser again

oracle/provider/crypto.go
Accidental print debug statement from a previous PR
---
I have...
I have...
=> style: Remove print

Dockerfile, config/config.go, config/config_test.go, price-feeder.example.toml
- Update the sample config with change made on the Umee side
- Enable nested env variable overrides from the config
- Add Dockerfile here instead of Ojo repo because it makes more sense
Matching Ojo PR: https://github.com/ojo-network/ojo/pull/103
=> ci: Env variable overrides

config/currency_provider_tracker.go
- Update osmosis api url in currency provider tracker to the new one
=> chore: update osmo url in currency provider tracker

go.mod
closes: #XXXX
---
I have...
I have...
=> chore: remove unnecessary replace

cmd/price-feeder.go
closes: #XXXX
---
I have...
I have...
=> feat: Add skip provider check flag to umee branch

CHANGELOG.md, price-feeder.example.toml
closes: #XXXX
---
I have...
I have...
=> feat: Add CHANGELOG.md

.goreleaser.yml
closes: #XXXX
---
I have...
I have...
=> fix: umee goreleaser

README.md
Improve docs about PF usage.
Backport from https://github.com/umee-network/umee/pull/1945
=> docs: adding more instructions about price feeder config

.github/workflows/publish-umee-image.yml
-Add github action to auto push umee e2e docker image
=> ci: Add github action to auto push umee e2e docker image

.github/workflows/publish-umee-image.yml
closes: #XXXX
---
I have...
I have...
=> ci: Update umee docker repo

oracle/client/tx.go, price-feeder.example.toml
closes: #XXXX
---
I have...
I have...
=> fix: increases gas in BroadcastTx for umee e2e test to work in experimental mode

.github/workflows/publish-umee-image.yml, price-feeder.example.toml
closes: #XXXX
---
I have...
I have...
=> chore: adding akt,juno,luna to pf config

oracle/provider/osmosisv2.go, price-feeder.example.toml
Fixes failing tests like the one in the [fin provider backport](https://github.com/ojo-network/price-feeder/pull/85)
---
I have...
I have...
=> chore: update osmosis API endpoint

price-feeder.example.toml
closes: #XXXX
---
I have...
I have...
=> chore: adding stkATOM config to pf config

price-feeder.example.toml
adding osmov2 provider to price-feeder config
---
I have...
I have...
=> chore: add osmov2 provider

oracle/convert.go, oracle/convert_test.go, oracle/oracle.go, oracle/oracle_test.go
- Log error instead of failing on failed USD conversion
- Update ticker conversion algorithm to fix applying multiple conversion rates
closes: https://github.com/ojo-network/price-feeder/issues/93
=> feat: log error instead of failing on failed USD conversion

price-feeder.example.toml
closes: #XXXX
---
I have...
I have...
=> chore: add qATOM configuration 

price-feeder.example.toml
closes: #XXXX
---
I have...
I have...
=> chore: adding cbETH pf config

.github/dependabot.yml
closes: #117 
---
I have...
I have...
=> ci: Remove umee backport in main dependabot

.github/dependabot.yml
closes: #117 
---
I have...
I have...
=> ci: Umee branch dependabot

config/currency_provider_tracker.go, oracle/provider/osmosisv2.go
closes: #XXXX
---
I have...
I have...
=> feat: Swap osmosis endpoint with ojo endpoint

price-feeder.example.toml
closes: #XXXX
---
I have...
I have...
=> feat: Add assets from our crescent api to example config

oracle/provider/crypto.go, oracle/provider/crypto_test.go
closes: #XXXX
---
I have...
I have...
=> fix: remove converting crypto.com candle timestamps to milliseconds

oracle/provider/crypto.go, oracle/provider/provider.go, oracle/util.go, oracle/util_test.go
Another fix compared to https://github.com/ojo-network/price-feeder/pull/138, which is more specific to crypto.com
---
I have...
I have...
=> fix: extend crypto.com candle period

price-feeder.example.toml
Price feeder config fixes for pricing out some assets
---
I have...
I have...
=> fix: price-feeder config changes

price-feeder.example.toml
- Add ETH,BTC,OSMO to sample config
---
I have...
I have...
=> chore: add ETH,BTC,OSMO to sample config

.golangci.yml
We don't have a config file anyway 🤷🏻 
---
I have...
I have...
=> chore: remove depguard

price-feeder.example.toml
Add DAI, stAtom, stOsmo
---
I have...
I have...
=> chore: add DAI, stAtom, stOsmo

price-feeder.example.toml
closes: #XXXX
---
I have...
I have...
=> chore: add SCRT, JUNO, and stJUNO to example config

config/config_test.go, config/supported_assets.go, price-feeder.example.toml
Add stUMEE pricing to sample config.
---
I have...
I have...
=> chore: [umee] add stUMEE to sample config

oracle/oracle.go, oracle/provider/price_store.go
- When initialization of a provider fails log the error and skip over it instead of causing an oracle tick failure.
- Minor updates to log message levels
closes: #191 
---
I have...
I have...
=> chore: error handling updates

price-feeder.example.toml
closes: #XXXX
---
I have...
I have...
=> feat: rETH config

README.md, config/currency_provider_tracker.go, config/supported_assets.go, oracle/oracle.go, oracle/oracle_test.go, oracle/provider/osmosis.go, oracle/provider/osmosis_test.go, oracle/provider/provider.go, oracle/util_test.go, price-feeder.example.toml
closes: #169 
---
I have...
I have...
=> style: change OsmosisV2 provider to Osmosis

config/config.go, price-feeder.example.toml
closes: #XXXX
---
I have...
I have...
=> fix: ProviderPair() method in config loader

go.mod, go.sum
closes: #XXXX
---
I have...
I have...
=> build: Update ojo to v0.2.0

price-feeder.example.toml
closes: #XXXX
---
I have...
I have...
=> chore: adding SOMM and NCT to pf v2.1.6 config

price-feeder.example.toml
closes: #XXXX
---
I have...
I have...
=> fix: fix the gas issue

umee-provider-config/currency-pairs.toml
Fixes the cmst & stkatom configs and moves them to osmosis
---
I have...
I have...
=> fix: cmst & stkatom configs

umee-provider-config/currency-pairs.toml, umee-provider-config/deviation-thresholds.toml, umee-provider-config/endpoints.toml
configuration for NCT and SOMM
```
base = "NCT"
providers = [
"osmosis",
]
quote = "OSMO"
base = "SOMM"
providers = [
"osmosis",
]
quote = "OSMO"
base = "SOMM"
providers = [
"gate",
]
quote = "USDT"
```
---
I have...
I have...
=> chore: adding NCT and SOMM config

umee-provider-config/endpoints.toml
The current uniswap endpoint is not reliable and this PR updates it to a better one.
---
I have...
I have...
=> chore: update uniswap umee endpoint

umee-provider-config/currency-pairs.toml, umee-provider-config/deviation-thresholds.toml
```
[[deviation_thresholds]]
base = "STARS"
threshold = "2"
base = "STARS"
providers = [
"osmosis",
]
quote = "ATOM"
base = "STARS"
providers = [
"osmosis",
]
quote = "OSMO"
```
---
I have...
I have...
=> chore: adding stars(stargaze) to pf config

umee-provider-config/currency-pairs.toml, umee-provider-config/deviation-thresholds.toml
closes: #XXXX
---
I have...
I have...
=> chore: add tia, wsteth, and sfrxeth to umee config

oracle/provider/gate.go
- Updates a validation check on the candle payload from the gate provider. 
---
I have...
I have...
=> fix: update gate provider candle parsing

price-feeder.example.toml
Updates the recommended gas_adjustment config value
---
I have...
I have...
=> chore(config): update recommended gas_adjustment

config/config.go
closes: #XXXX
---
I have...
I have...
=> fix: lint for #337

umee-provider-config/currency-pairs.toml, umee-provider-config/deviation-thresholds.toml
closes: #XXXX
---
I have...
I have...
=> chore: adding strd to umee pf config

oracle/client/client.go
=> fix: prevote gas allocation

config/config_test.go, ojo-provider-config/currency-pairs.toml, oracle/provider/price_store.go
closes: #XXXX
---
I have...
I have...
=> ci: update tests

config/supported_assets.go, umee-provider-config/currency-pairs.toml, umee-provider-config/deviation-thresholds.toml
1. Supporting TIA as a quote config 
---
I have...
I have...
=> chore:  support TIA as quote for milkTIA asset

umee-provider-config/currency-pairs.toml, umee-provider-config/deviation-thresholds.toml
```toml
base = "milkTIA"
providers = [
"osmosis",
]
quote = "TIA"
base = "milkTIA"
providers = [
"osmosis",
]
quote = "USDC"
```
```toml
[[deviation_thresholds]]
base = "milkTIA"
threshold = "2"
```
---
I have...
I have...
=> chore: add milkTIA config to mainnet

umee-provider-config/currency-pairs.toml
1. removing the crescent provider for IST 
---
I have...
I have...
=> chore: update the IST pf config 

umee-provider-config/currency-pairs.toml, umee-provider-config/deviation-thresholds.toml
Adding stTIA config 
```toml
base = "stTIA"
providers = [
"osmosis",
]
quote = "TIA"
```
---
I have...
I have...
=> chore: adding stTiA pf config mainnet

config/supported_assets.go
we are adding `dydx`  as a supportted conversion token for `stDYDX`
---
I have...
I have...
=> chore: support dydx as a conversion token

umee-provider-config/currency-pairs.toml, umee-provider-config/deviation-thresholds.toml
```toml
base = "BLD"
providers = [
"osmosis",
]
quote = "OSMO"
base = "BLD"
providers = [
"gate",
]
quote = "USDT"
base = "stDYDX"
providers = [
"osmosis",
]
quote = "DYDX"
```
---
I have...
I have...
=> chore: adding BLD and stDYDX to mainnet

config/supported_assets.go
closes: #XXXX
---
I have...
I have...
=> fix: update stjuno conversion path

umee-provider-config/currency-pairs.toml, umee-provider-config/deviation-thresholds.toml
```toml
base = "KAVA"
quote = "USDT"
providers = ["binance", "gate", "bitget", "binanceus", "crypto"]
base = "KAVA"
quote = "USD"
providers = ["kraken", "coinbase", "crypto"]
```
---
I have...
I have...
=> chore: adding KAVA to mainnet

umee-provider-config/currency-pairs.toml, umee-provider-config/deviation-thresholds.toml
```toml
base = "SEI"
providers = [
"binance",
"bitget",
"gate",
]
quote = "USDT"
base = "SEI"
providers = [
"kraken",
"crypto",
"coinbase",
]
quote = "USD"
```
---
I have...
I have...
=> chore: adding sei pf config to mainnet

config/supported_assets.go
closes: #XXXX
---
I have...
I have...
=> feat: Add tia conversion path

oracle/provider/uniswap.go
change the uniswap provider endpoint
---
I have...
I have...
=> fix: fix the uniswap provider issue
