ojo-network/price-feeder

oracle/oracle.go, oracle/oracle_test.go, oracle/provider/binance.go, oracle/provider/bitget.go, oracle/provider/coinbase.go, oracle/provider/crypto.go, oracle/provider/gate.go, oracle/provider/huobi.go, oracle/provider/kraken.go, oracle/provider/mexc.go, oracle/provider/mock.go, oracle/provider/okx.go, oracle/provider/osmosis.go, oracle/provider/osmosisv2.go, oracle/provider/polygon.go, oracle/provider/provider.go, tests/integration/provider_test.go
- Some of the tests were accidentally starting a websocket connection and only meaning to initialize the provider object. This PR moves starting the websocket connection to a separate function so we can test the providers without connecting to the actual websocket connection.
- Hopefully also fixes the race condition seen in the test suite https://github.com/ojo-network/price-feeder/actions/runs/4295545469/jobs/7486105704
=> fix: Move starting the websocket connection to a separate func

.github/workflows/build.yml, .github/workflows/codeql-analysis.yml, .github/workflows/linkchecker.yml, .github/workflows/lint.yml, .github/workflows/price-feeder-release.yml, .github/workflows/tests.yml, .goreleaser.yml, .mergify.yml
=> ci: Update umee branch goreleaser

cmd/price-feeder.go
Sometimes the coingecko API does not work and it prevents the price-feeder from starting. This causes flakiness with the e2e tests and pauses during local development.
- Add a flag to skip the coingecko provider check
=> feat: Add skip provider check flag

.github/workflows/publish-image.yml, Makefile
- Add github action for pushing new e2e test images after PRs are merged to master
closes the ojo side of: https://github.com/ojo-network/price-feeder/issues/50
=> ci: github action for pushing the docker image

oracle/util.go, oracle/util_test.go
Currently, if candles are considered to be in the future (validator’s clock time < provider’s clock time), they will be computed as a part of the TVWAP. This might result in problematic consequences as the higher the clock deviation is, the more candles can be added to the TVWAP calculation and thus reduce the precision of the calculated value.
- Filter any possible future prices during tvwap calculations.
fixes: https://github.com/ojo-network/price-feeder/issues/91
=> fix: Filter future prices in tvwap calculation

tests/integration/price_test.go, tests/integration/provider_test.go
Speed up integration tests.
- The parallel feature of the go test suite don't seem to play nice with github actions. Testing moving it to a simple go routine and wait group instead.
- Update the maxCoeficientOfVariation from 0.1 to 0.2 since the OSMO and BTC price trigger false positives.
---
I have...
I have...
=> chore: speed up integration tests

oracle/oracle.go, oracle/oracle_test.go
Fixes the exchange rate vote string which ojo parses into rates
Goes back to the format `ATOM:9.58,ETH:42.5` format instead of `ATOMUSD:9.58,ETHUSD:42.5`
---
I have...
I have...
=> fix: exchange rate vote string

config/config.go, config/config_test.go, config/supported_assets.go, oracle/convert.go, oracle/convert_test.go, oracle/oracle.go, oracle/oracle_test.go, tests/integration/coin_market_cap.go, tests/integration/price_test.go
- Converted the `SupportedQuotes` map into a `SupportedConversions` map that uses currency pairs to determine what pairs can be used for converting other candles/tickers.
- Created the new `validateCurrencyPairs()` function in the config to check all non-USD quoted assets against the supported conversions list.
- Completely re-wrote the convert.go file to allow for multiple conversion paths by initially computing all possible conversion and then converting candles/tickers as needed.
- Instead of falling back to tickers when no candles are available it now falls back on a per denom basis.
Part 3 / 3: https://github.com/ojo-network/price-feeder/issues/105
---
please add links to any relevant follow up …
=> refactor: allow for multiple conversion paths

.gitignore, .goreleaser.yml, cmd/version.go, scripts/extract_dependency_versions.sh
Implements the previously unimplemented version number and cosmos sdk version output in the `price-feeder version` CLI output
closes: #216 
---
I have...
I have...
=> fix: price-feeder and cosmos sdk version output

oracle/provider/okx.go, oracle/provider/websocket_controller.go, tests/integration/provider_test.go
- Okx provider changed the URL to use for candlestick data from "/public" to "/business". Now we need to handle different URL's for difference subscription messages.
- Also updated the provider integration test to display both candle and ticker errors if both of them fail.
---
I have...
I have...
=> fix: okx breaking URL change

ojo-provider-config/endpoints.toml, oracle/oracle.go
Modifies the `Oracle.SetPrices()` go routine such that when both the ticker and candle prices are missing for one asset pair it does not skip other existing valid pairs.
---
I have...
I have...
=> fix: Don't fail the entire provider when one asset is missing

umee-provider-config/currency-pairs.toml
- Remove the single uniswap LINK provider so it does not confuse validators with error messages
- Remove the okx provider for UMEE/USDT
- Add the mexc provider for UMEE/USDT
---
I have...
I have...
=> chore: Remove LINK and update Umee providers

.golangci.yml, ojo-provider-config/currency-pairs.toml, ojo-provider-config/endpoints.toml, oracle/oracle.go, oracle/provider/uniswap.go, oracle/provider/uniswap_test.go, tests/integration/provider_test.go
- The old uniswap provider was using a polling mechanism to retrieve prices from a product called "The Graph". This has been replaced with a websocket API similar to the osmosis and kujira APIs. It is a strait up copy paste from the osmosis provider replacing "osmosis" with "uniswap".
- Updated the config to remove unnecessary uniswap config values
---
I have...
I have...
=> feat: Update uniswap provider to use new websocket api

config/supported_assets.go, ojo-provider-config/currency-pairs.toml, oracle/oracle.go, oracle/provider/astroport.go, oracle/provider/astroport_test.go
Adds an astroport provider that periodically polls tickers.
Astroport's API currently does not support websockets or candle data. 
Note: The test here has a TODO to make it more comprenehsive.
Also, the provider only supports tickers atm.
---
I have...
I have...
=> feat: astroport provider

config/currency_provider_tracker.go, oracle/provider/astroport.go, oracle/provider/astroport_test.go
… for quote symbol field
closes: #XXXX
---
I have...
I have...
=> fix: Handle astroport asset response returning inconsistent data type

CHANGELOG.md, README.md, cmd/price-feeder.go, config/config.go, oracle/client/client.go, oracle/oracle.go, price-feeder.example.toml
Instead of having one config for a fixed gas amount, we support two configs:
* `gas_prevote` for the prevote transactions
* `gas_vote` for the vote transactions
=> feat: support fixed gas for vote and prevote transactions

cmd/version.go, config/load.go, oracle/provider/astroport_test.go, oracle/provider/mexc.go, oracle/provider/mexc_test.go, oracle/types/currency.go, router/v1/router.go
closes: #XXXX
---
I have...
I have...
=> fix: Update mexc provider to use v3 api

README.md, umee-provider-config/endpoints.toml
Following `ERR failed to initialize binance provider ` reported by a new validator, let's update the docs.
=> docs: update config documentation + note about Binance US

README.md, ojo-provider-config/endpoints.toml
* docs: update config documentation + note about Binance US
* lint
closes: #XXXX
---
I have...
I have...
=> docs: update config documentation + note about Binance US (#378)

CHANGELOG.md, umee-provider-config/currency-pairs.toml, umee-provider-config/deviation-thresholds.toml
```toml
base = "NTRN"
quote = "USDT"
providers = [ "binance", "bitget", "gate",]
[[deviation_thresholds]]
base = "NTRN"
threshold = "2"
```
---
I have...
I have...
=> chore: adding pf config of NTRN

config/supported_assets.go, oracle/convert.go, oracle/util.go
closes: #XXXX
---
I have...
I have...
=> feat: Add WSTETH/WETH as supported conversion
